import {
  siArm,
  siCaddy,
  siCapacitor,
  siC,
  siDassaultsystemes,
  siDjango,
  siDocker,
  siDotnet,
  siEslint,
  siExpo,
  siExpress,
  siFigma,
  siGit,
  siGithub,
  siGithubactions,
  siGodotengine,
  siHtml5,
  siCss,
  siIonic,
  siJavascript,
  siJsonwebtokens,
  siK6,
  siLeaflet,
  siLinux,
  siApachemaven,
  siMistralai,
  siMui,
  siMysql,
  siNeon,
  siNestjs,
  siNextdotjs,
  siNginx,
  siNodedotjs,
  siNxp,
  siOpencv,
  siOpenjdk,
  siPhp,
  siPinia,
  siPostgresql,
  siPrimevue,
  siPrisma,
  siPuppeteer,
  siPytest,
  siPython,
  siQt,
  siRaspberrypi,
  siReact,
  siReacthookform,
  siReactquery,
  siRender,
  siRos,
  siRuff,
  siStmicroelectronics,
  siStripe,
  siSupabase,
  siSymfony,
  siTailwindcss,
  siTypescript,
  siVercel,
  siVite,
  siVitest,
  siVuedotjs,
} from "simple-icons";
import type { SimpleIcon } from "simple-icons";

export interface DefinitionTechno {
  nom: string;
  icone?: SimpleIcon;
}

const definitions = {
  // Chaîne, conteneurs, hébergement
  githubactions: { nom: "GitHub Actions", icone: siGithubactions },
  docker: { nom: "Docker", icone: siDocker },
  nginx: { nom: "Nginx", icone: siNginx },
  caddy: { nom: "Caddy", icone: siCaddy },
  render: { nom: "Render", icone: siRender },
  vercel: { nom: "Vercel", icone: siVercel },
  supabase: { nom: "Supabase", icone: siSupabase },
  neon: { nom: "Neon", icone: siNeon },
  aiven: { nom: "Aiven" },
  linux: { nom: "Linux", icone: siLinux },
  git: { nom: "Git", icone: siGit },
  github: { nom: "GitHub", icone: siGithub },
  // Qualité
  pytest: { nom: "pytest", icone: siPytest },
  vitest: { nom: "Vitest", icone: siVitest },
  ruff: { nom: "Ruff", icone: siRuff },
  eslint: { nom: "ESLint", icone: siEslint },
  k6: { nom: "k6", icone: siK6 },
  puppeteer: { nom: "Puppeteer", icone: siPuppeteer },
  // Back-end et données
  nestjs: { nom: "NestJS", icone: siNestjs },
  django: { nom: "Django", icone: siDjango },
  express: { nom: "Express", icone: siExpress },
  nextjs: { nom: "Next.js", icone: siNextdotjs },
  node: { nom: "Node.js", icone: siNodedotjs },
  python: { nom: "Python", icone: siPython },
  dotnet: { nom: ".NET", icone: siDotnet },
  symfony: { nom: "Symfony", icone: siSymfony },
  php: { nom: "PHP", icone: siPhp },
  prisma: { nom: "Prisma", icone: siPrisma },
  postgresql: { nom: "PostgreSQL", icone: siPostgresql },
  mysql: { nom: "MySQL", icone: siMysql },
  jwt: { nom: "JWT", icone: siJsonwebtokens },
  stripe: { nom: "Stripe", icone: siStripe },
  mistral: { nom: "Mistral AI", icone: siMistralai },
  // Front et mobile
  react: { nom: "React", icone: siReact },
  vue: { nom: "Vue", icone: siVuedotjs },
  typescript: { nom: "TypeScript", icone: siTypescript },
  javascript: { nom: "JavaScript", icone: siJavascript },
  html: { nom: "HTML", icone: siHtml5 },
  css: { nom: "CSS", icone: siCss },
  vite: { nom: "Vite", icone: siVite },
  mui: { nom: "Material UI", icone: siMui },
  primevue: { nom: "PrimeVue", icone: siPrimevue },
  tailwind: { nom: "Tailwind CSS", icone: siTailwindcss },
  reactquery: { nom: "TanStack Query", icone: siReactquery },
  reacthookform: { nom: "React Hook Form", icone: siReacthookform },
  pinia: { nom: "Pinia", icone: siPinia },
  expo: { nom: "Expo", icone: siExpo },
  ionic: { nom: "Ionic", icone: siIonic },
  capacitor: { nom: "Capacitor", icone: siCapacitor },
  leaflet: { nom: "Leaflet", icone: siLeaflet },
  figma: { nom: "Figma", icone: siFigma },
  // Embarqué et robotique
  c: { nom: "C", icone: siC },
  stm32: { nom: "STM32", icone: siStmicroelectronics },
  arm: { nom: "Arm Cortex-M", icone: siArm },
  nxp: { nom: "NXP", icone: siNxp },
  freertos: { nom: "FreeRTOS" },
  ros: { nom: "ROS 2", icone: siRos },
  raspberrypi: { nom: "Raspberry Pi", icone: siRaspberrypi },
  opencv: { nom: "OpenCV", icone: siOpencv },
  qt: { nom: "PyQt", icone: siQt },
  solidworks: { nom: "SolidWorks", icone: siDassaultsystemes },
  godot: { nom: "Godot", icone: siGodotengine },
  // Logiciel
  java: { nom: "Java", icone: siOpenjdk },
  cpp: { nom: "C++" },
  vhdl: { nom: "VHDL" },
  fpga: { nom: "FPGA iCE40" },
  can: { nom: "Bus CAN" },
  maven: { nom: "Maven", icone: siApachemaven },
} satisfies Record<string, DefinitionTechno>;

export type Techno = keyof typeof definitions;

export const TECHNOS: Record<Techno, DefinitionTechno> = definitions;
